# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a22386e863f6b0c81f18a61195d7c1c7c3879ddb0db6a463ed52dd1e9ee24a960e58d37df7c9c4866b5507a09d26e40ba23478f717a97de5dd317db9776e839d

test:
  secret_key_base: feb114519ed2e20c1c56f6a0011e5842f470b1c7f92ae9f723844d9ae7a2ac79046bdfc0a5ee7a14fb2870048ce1a1770f0a4e4b1ad279f540b3d008f4655c1d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
